### ISSUE TITLE
fresh OpenWrt compatibility

### ISSUE THREAD

**Issue by bam80** [AndreBL/ip6neigh#18]
Thanks for the project,
does it work with recent OpenWrt versions?

**Comment by cvmiller** [comment]
Good question, I'll have to give it a try

**Comment by cvmiller** [comment]
Sorry, it took me a while to make a router available for test. I just upgraded a router to 23.05.0rc4, and I am happy to see if you follow the directions on installing `ip6neigh` then it will work, mostly.

The command: `ip6neigh oui download` fails because the oui website is no longer responding. However, I have a temporary fix for this by changing the URL in the `ip6neigh` script.

```
-	curl -# -S -f -k -o '/tmp/oui-raw.txt' 'https://linuxnet.ca/ieee/oui/nmap-mac-prefixes' || exit 2
+	curl -# -S -f -k -o '/tmp/oui-raw.txt' 'http://www.makikiweb.com/ieee/oui/nmap-mac-prefixes' || exit 2
```

Once the `ip6neigh` script has been edited, you can then run `ip6neigh oui download` command and it will work

**Comment by bam80** [comment]
Thanks, will you fix the URL in this repo?

**Comment by cvmiller** [comment]
I just copied the OUI file to my server (hence the temporary fix) for now. I'd like to find a site that regularly updates the OUI file, and then update the script in the repo then.

**Comment by cvmiller** [comment]
Updated Documentation and ip6neigh.sh to pull down a maintained OUI database (from NMAP). Closing.
