### ISSUE TITLE
Rarely used IPv6 device addresses drop out of DNS

### ISSUE THREAD

**Issue by simpz** [AndreBL/ip6neigh#2]
This maybe by design, but devices that are rarely used drop out of IPv6 DNS.

For example, my WiFi extender and server out of band remote access device drop out of IPv6 DNS. If I reboot these devices, they go back into DNS for several hours.

Also pinging these devices by the IPv6 address on the router, brings them back into DNS.

This maybe a feature, i.e. the table has to be scavenged some how.

**Comment by AndreBL** [comment]
Hi Simpz,

Thanks for the feedback.

The "#Discovered IPv6 neighbors" section of the hosts file is kept in sync with the router's neighbors table. Addresses that are not performing any network activity for a long time (more than 1 day, I think) are recycled from the neighbor's table by the router, so they end up being removed from ip6neigh as well. This is normal behavior, otherwise the table would grow indefinitely with old and unused addresses.

If you need to (or simply want to, for organization) have your WiFi extender and server addresses permanently named by ip6neigh, take a look at the examples at https://github.com/AndreBL/ip6neigh/blob/master/etc/config/dhcp . They show how to do this. Description here: https://github.com/AndreBL/ip6neigh#config-predefined-hosts .
Really recommended for servers.

**Comment by simpz** [comment]
The strange thing is these devices  that drop out are already permanently named in /etc/config/dhcp e.g.

config host
	option name 'devowireless'
	option mac '30:d3:2e:53:d8:1d'
	option slac '1'

**Comment by AndreBL** [comment]
There's a typo there. It's option **slaac** with double 'a'.

**Comment by simpz** [comment]
Ah sorry, my stupid mistake. The ones that have dropped out have this typo. Corrected and so far so good. 

Thanks again

**Comment by AndreBL** [comment]
Good to know that you found the problem. You can always check whether a host is in the static list by typing: ip6neigh list
